<a href="https://colab.research.google.com/github/py222015328/CEE2/blob/main/10_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução ao NumPy

O **NumPy** é uma das bibliotecas fundamentais para a computação científica em Python, sendo amplamente usada para trabalhar com arrays multidimensionais e operações matemáticas de alto desempenho. Ela fornece ferramentas para manipulação de dados, álgebra linear, estatísticas, etc.

- Esta é uma rápida introdução ao NumPy que demonstra como matrizes n-dimensionais são representadas e podem ser manipulatadas.

- Mais detalhes podem ser encontrados no tutorial: https://numpy.org/devdocs/user/quickstart.html

A classe de matrizes do NumPy é chamada `ndarray` (ou simplesmente `array`). Note que `numpy.array` não é o mesmo que a classe `array.array` da biblioteca padrão do Python, a qual manipula apenas vetores unidimensionais e oferece menos funcionalidades.

Os principais atributos de um objeto `ndarray` são:

- `ndarray.ndim`: número de dimensões da matriz.

- `ndarray.shape`: as dimensões da matriz. Uma tupla de inteiros indicando o tamanho em cada dimensão. Para uma matriz com linhas e colunas, o resultado será `(n, m)`. O tamanho da tupla é o mesmo que o número de eixos `ndim`.

- `ndarray.size`: o número total de elementos na matriz. É igual ao produtos dos elementos do shape.

- `ndarray.dtype`: um objeto que descreve o tipo dos elementos da matriz. Pode ser criado usando os tipos padrão do Python. Além destes, NumPy define outros tipos como `numpy.int32`, `numpy.int16`, e `numpy.float64`.

- `ndarray.reshape`: permite alterar a dimensão de um array.


## Criando Arrays

O `array` é a estrutura de dados central do NumPy. Ele é mais eficiente e flexível do que as listas Python tradicionais.

Importanto a biblioteca com
```python
import NumPy as np
```

Alguns módulos mais importantes da biblioteca são:

* `np.array()`: cria arrays a partir de listas;
* `np.zeros()`: cria um array preenchido com zeros;
* `np.arange()`: cria um array com uma sequência de valores;
* `np.linspace()`: cria um array de valores uniformemente espaçados.

Veja os exemplo abaixo:

In [1]:
# Criando um array a partir de uma lista:

import numpy as np

a = np.array([1, 2, 3, 4])
print(a)                  # Saída: [1 2 3 4] (vetor)
print("type:", type(a))   # Saída: <class 'numpy.ndarray'>
print("dtype:", a.dtype)  # Saída: int64
print("size:", a.size)    # Saída: 4
print("ndim:", a.ndim)    # Saída: 1
print("shape:", a.shape)  # Saída: (4,)

[1 2 3 4]
type: <class 'numpy.ndarray'>
dtype: int64
size: 4
ndim: 1
shape: (4,)


In [3]:
# Arrays de múltiplas dimensões:

import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)                  # Saída: [[1 2 3] [4 5 6]] (matriz)
print("type:", type(b))   # Saída: <class 'numpy.ndarray'>
print("dtype:", b.dtype)  # Saída: int64
print("size:", b.size)    # Saída: 6
print("ndim:", b.ndim)    # Saída: 2
print("shape:", b.shape)  # Saída: (2, 3)

[[1 2 3]
 [4 5 6]]
type: <class 'numpy.ndarray'>
dtype: int64
size: 6
ndim: 2
shape: (2, 3)


In [4]:
# Arrays com valores predefinidos

import numpy as np

## Array de zeros:
print("--zeros--")
zeros = np.zeros((2, 3))
print("dtype:", zeros.dtype)  # Saída: float64
print(zeros)                  # Saída: [[0. 0. 0.] [0. 0. 0.]]
print("-----")

## Array de uns:
print("--ones--")
ones = np.ones((2, 2))    # Matriz 2x2 de uns
print(ones)               # Saída: [[1. 1.] [1. 1.]]
print("-----")

--zeros--
dtype: float64
[[0. 0. 0.]
 [0. 0. 0.]]
-----
--ones--
[[1. 1.]
 [1. 1.]]
-----


Para criar sequências de números o NumPy fornece a função `arange()` que é análoga à função `range()`.

In [5]:
# Arrays sequenciais

import numpy as np

## Array com valores de 0 a 9:
print("--seq1--")
seq1 = np.arange(10)
print(seq1)                # Saída: [0 1 2 3 4 5 6 7 8 9]
print("-----")

# Cria um vetor com elementos de 10 a 30 com passo 5.
print("--seq2--")
seq2 = np.arange(10, 30, 5)
print(seq2)               # Saída: [10 15 20 25]
print("-----")

## Array com valores igualmente espaçados:
print("--lin--")
lin_space = np.linspace(0, 1, 5)  # 5 valores igualmente espaçados entre 0 e 1
print(lin_space)          # Saída: [0.   0.25 0.5  0.75 1.  ]
print("-----")

--seq1--
[0 1 2 3 4 5 6 7 8 9]
-----
--seq2--
[10 15 20 25]
-----
--lin--
[0.   0.25 0.5  0.75 1.  ]
-----


Ao usar `arange()` com números não inteiros pode não ser possível predizer a quantidade de elementos obtidos devido à precisão do ponto flutuante. Melhor usar `linspace()` passando o número de elementos:

In [6]:
import numpy as np

x = np.linspace(0, 2 * np.pi, 30)  # Cria um vetor com 30 elementos entre 0 e 2pi.
print(x)

[0.         0.21666156 0.43332312 0.64998469 0.86664625 1.08330781
 1.29996937 1.51663094 1.7332925  1.94995406 2.16661562 2.38327719
 2.59993875 2.81660031 3.03326187 3.24992343 3.466585   3.68324656
 3.89990812 4.11656968 4.33323125 4.54989281 4.76655437 4.98321593
 5.1998775  5.41653906 5.63320062 5.84986218 6.06652374 6.28318531]


## Dimensão

A dimensão de um array pode ser alterada utilizando o atributo `.reshape`. Veja o exemplo:

In [7]:
import numpy as np

## vetor
seq = np.arange(12)
print(seq)  # Saída: [0 1 2 3 4 5 6 7 8 9 10 11]
print("-----")

## matriz 3x4
a = seq.reshape(3, 4)
print(a)  # Saída: [[ 0  1  2  3] [ 4  5  6  7] [ 8  9 10 11]]
print("-----")

## matriz 4x3
b = seq.reshape(4, 3)
print(b)  # Saída: [[ 0  1  2] [ 3  4  5] [ 6  7  8] [ 9 10 11]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
-----
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-----
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Existem diversas formas de se criar matrizes:

In [8]:
# O tipo é deduzido dos elementos.

import numpy as np
a = np.array([2, 3, 4])
print(a)
print(a.dtype)     ## exibe: dtype('int64')

print("-----")

b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)    ## exibe: dtype('float64')

[2 3 4]
int64
-----
[1.2 3.5 5.1]
float64


In [9]:
# O tipo da matriz pode ser especificado explicitamente na criação:

import numpy as np

a = np.array([2, 3, 4], dtype= float)
print(a)
a.dtype     ## exibe: dtype('float64')

print("-----")

c = np.array([[1, 2], [3, 4]], dtype= complex)
c

[2. 3. 4.]
-----


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Um erro frequente consiste em chamar array com múltiplos argumentos, ao invés de uma sequência.

In [10]:
#a = np.array(1, 2, 3, 4)     # TypeError
a = np.array([1, 2, 3, 4])   # CORRETO!

O NumPy exibe a matriz de forma similar à listas aninhadas com o seguinte layout:

- O último eixo é exibido da esquerda para a direita;

- O penúltimo eixo é exibido de cima para baixo;

- Os demais eixos são exibidos de cima para baixo separados por uma linha em branco;

Vetores (unidimensional) são exibidos como vetorlinhas, matrizes bidimensionais como matrizes e matrizes tridimensionais como lista de matrizes.

In [11]:
a = np.arange(6)    # Cria um vetor com 6 elementos de 0 a 5.
print(a)

[0 1 2 3 4 5]


In [12]:
b = np.arange(12).reshape(4, 3)    # Cria uma matriz 4x3.
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
c = np.arange(24).reshape(2, 3, 4)  # Cria uma matriz tridimensional: 2x3x4.
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Se a matriz é muito grande o NumPy automaticamente omite a parte central da matriz:

In [14]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [19]:
print(np.arange(1000).reshape(10, 100))

[[  0   1   2 ...  97  98  99]
 [100 101 102 ... 197 198 199]
 [200 201 202 ... 297 298 299]
 ...
 [700 701 702 ... 797 798 799]
 [800 801 802 ... 897 898 899]
 [900 901 902 ... 997 998 999]]


Para disabilitar, mude a opção usando:

```python
np.set_printoptions(threshold= sys.maxsize)
```

In [34]:
## exemplo

import sys

np.set_printoptions(threshold= sys.maxsize)

print(np.arange(100).reshape(10, 10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


## Exercício 1

a) Crie um array de zeros com forma 3x3.

b) Crie um array com números de 1 a 20, com passo de 3.


In [50]:
import numpy as np

a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
b = np.arange(1,20,3)
print(b)

[ 1  4  7 10 13 16 19]


## Operações básicas

Operadores aritméticos são aplicados em cada elemento. Uma nova matriz com o resultado é criada.

In [21]:
import numpy as np

a = np.array([2, 5, 4, 0])    # Cria um vetor com os vetores passados.
b = np.arange(4)              # Cria um vetor com os valores 0, 1, 2, 3.

print(a, "\n")                # Exibe o vetor a.
print(a+2, "\n")              # Adição elemento a elemento.
print(a+b, "\n")              # Adição elemento a elemento.
print(a-b, "\n")              # Subtração elemento a elemento.
print(b**2, "\n")             # Exibe o vetor com os quadrados dos elementos de b.
print(10 * np.sin(a), "\n")   # Calcula 10 vezes seno dos elementos do vetor a.
print(a < 3, "\n")            # Retorna um vetor booleano com True para cada elemento menor que 35.

[2 5 4 0] 

[4 7 6 2] 

[2 6 6 3] 

[ 2  4  2 -3] 

[0 1 4 9] 

[ 9.09297427 -9.58924275 -7.56802495  0.        ] 

[ True False False  True] 



O operador produto `*` opera elemento-a-elemento. O produto matricial é feito com `@` (Python >=3.5) ou com `dot()`:

In [22]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print(A * B, "\n")       # Produto elemento a elemento
print(A @ B, "\n")       # Produto matricial
print(A.dot(B), "\n")    # Produto matricial

[[2 0]
 [0 4]] 

[[5 4]
 [3 4]] 

[[5 4]
 [3 4]] 



Operações como `+=` e `*=` modifica uma matriz existente ao invés de criar uma nova.

In [23]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

A *= 3
print(A, "\n")

B += A
print(B, "\n")


[[3 3]
 [0 3]] 

[[5 3]
 [3 7]] 



Muitas operações são implementadas como métodos da classe `ndarray`.

In [24]:
A = np.array([[1, 1], [0, 1]])
print(A)
print("\n")
print(A.sum())    # Exibe a soma dos elementos.
print(A.min())    # Exibe o menor elemento.
print(A.max())    # Exibe o maior elemento.
print(A.mean())   # Exibe a média dos elementos.
print(A.std())    # Exibe o desvio padrão dos elementos.

[[1 1]
 [0 1]]


3
0
1
0.75
0.4330127018922193


Por padrão, estas operações tratam a matriz como uma lista de números. No entanto, é possível especificar o eixos para aplicar a operação:

In [25]:
B = np.arange(12).reshape(3, 4)
print( B, "\n" )

print( B.sum(axis= 0), "\n" )      # soma de cada coluna
print( B.min(axis= 1), "\n" )      # mínimo de cada linha
print( B.cumsum(axis= 1), "\n" )   # soma cumulativa em cada linha

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[12 15 18 21] 

[0 4 8] 

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]] 



## Exercício 2

* Crie um array com os valores `[10, 20, 30, 40, 50]`.
* Subtraia `5` de cada elemento e, em seguida, eleve ao quadrado cada valor.
* Apresente o vetor com a soma das colunas.

In [59]:
x = np.array([10,20,30,40,50])
print(x)
x1 = x - 5
print(x1)
x2 = x1**2
print(x2)
print(x1+x2)

[10 20 30 40 50]
[ 5 15 25 35 45]
[  25  225  625 1225 2025]
[  30  240  650 1260 2070]


## Funções universais

Funções matemáticas como `sin()`, `cos()` e `exp()`, chamadas de *funções universais* (`ufunc`), operam emento-a-elemento.

In [27]:
import numpy as np

B = np.arange(3)               # Cria um vetor com 3 elementos.
print(np.exp(B))               # Exibe o exponencial de cada elemento de B.
print(np.sqrt(B))              # Exibe a raiz quadrada de cada elemento de B.
C = np.array([2., -1., 4.])    # Cria um vetor com 3 elementos.
print(np.add(B, C))            # Exibe a soma entre os vetores B e C.

[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[2. 0. 6.]


## Indexação, fatiamento e iteração

Vetores unidimensionais podem ser indexados, fatiados e iterados como se fosse uma lista.

In [32]:
import numpy as np

a = np.arange(10)           # Gera um vetor dos cubos de 0 a 9.

print(a, "\n")              # Exibe o vetor 'a'.
print(a[2], "\n")           # Exibe o terceiro elemento do vetor 'a'.
print(a[2:5], "\n")         # Exibe os elementos nas posições 2, 3, 4.

[0 1 2 ... 7 8 9] 

2 

[2 3 4] 



In [35]:
a = np.arange(10)           # Gera um vetor dos cubos de 0 a 9.

print(a, "\n")              # Exibe o vetor 'a'.

a[:6:2] = 10              # Substitui os elementos nas posições 0, 2 e 4 por 10.

print(a, "\n")              # Exibe o vetor 'a'

print(a[::-1], "\n")        # Exibe o vetor 'a' invertido.

[0 1 2 3 4 5 6 7 8 9] 

[10  1 10  3 10  5  6  7  8  9] 

[ 9  8  7  6  5 10  3 10  1 10] 



Matrizes multidimensionais tem `1` índice por eixo:

In [30]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print( b,"\n")

print("Primeira linha:", b[0, :], "\n")

print("Terceira linha:", b[2, :], "\n")

print("Elemento (2,3):", b[1, 2], "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Primeira linha: [1 2 3] 

Terceira linha: [7 8 9] 

Elemento (2,3): 6 



In [36]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print( b,"\n")

print(b[:, 1], "\n")      # todas as linhas e 2a coluna

print(b[:2, 1], "\n")     # 1a e 2a linhas e 2a coluna.

print(b[1:, 2], "\n")     # 2a e 3a linhas e 3a coluna.

print(b[1:3, :])          # 2a e 3a linhas e todas as colunas.

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[2 5 8] 

[2 5] 

[6 9] 

[[4 5 6]
 [7 8 9]]


Se forem passados menos índices que o número de eixos, todos os demais estarão completos:

In [37]:
b[-1]     # A última linha. Equivale a b[-1, :]

array([7, 8, 9])

## Exercício 3

* Crie um array 3x3 com valores de 1 a 9.
* Extraia a segunda linha.
* Extraia o último elemento da primeira linha.


In [70]:
z = np.arange(9).reshape(3,3)
print(z,'\n')
print(z[1], '\n')
print(z[2,2])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[3 4 5] 

8


## Empilhamento e Desmembramento

Várias matrizes podem ser empilhadas em diferentes eixos:

In [38]:
import numpy as np

a = np.zeros((3,3))
b = np.ones((3,3))

print(a, "\n")                   # Exibe a matriz 'a'.
print(b, "\n")                   # Exibe a matriz 'b'.

print(np.vstack((a, b)), "\n")   # Empilha 'a' e 'b' na vertical.
print(np.hstack((a, b)), "\n")   # Empilha 'a' e 'b' na horizontal.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]] 



`hsplit()` permite desmembrar no eixo horizontal:

In [39]:
a = np.arange(18).reshape(3, 6)
print(a, "\n")

# Desmembra 'a' por colunas em 3 partes iguais
parte1, parte2, parte3 = np.hsplit( a, 3)
print("Parte 1:\n", parte1)
print("Parte 2:\n", parte2)
print("Parte 3:\n", parte3)


# Dividindo após a 2ª e a 5ª coluna
print("\n")
parte1, parte2, parte3 = np.hsplit(a, [1, 4])

print("Parte 1:\n", parte1)
print("Parte 2:\n", parte2)
print("Parte 3:\n", parte3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]] 

Parte 1:
 [[ 0  1]
 [ 6  7]
 [12 13]]
Parte 2:
 [[ 2  3]
 [ 8  9]
 [14 15]]
Parte 3:
 [[ 4  5]
 [10 11]
 [16 17]]


Parte 1:
 [[ 0]
 [ 6]
 [12]]
Parte 2:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
Parte 3:
 [[ 4  5]
 [10 11]
 [16 17]]


`vsplit()` desmembra na vertical e `array_split()` permite escolher o eixo.

## Exercício 4

1. Crie dois arrays 1D, `a` e `b`, com valores de 1 a 5 e de 6 a 10, respectivamente.
1. Empilhe `a` e `b` verticalmente para formar um array 2D.
1. Em seguida, empilhe `a` e `b` horizontalmente para formar um array 1x10.

Dica: Use np.vstack() para empilhamento vertical e np.hstack() para empilhamento horizontal.

## Cópias e visualizações

Algumas operações copiam a matriz outras não. Atribuições não fazem cópias de objetos ou dados.

Veja os exemplos.

In [40]:
import numpy as np

A = np.zeros((3,3))

B = A          ## atribuição não é cópia

A[:,1] = 100   ## note que ao alterar "A" a matriz "B" também será alterada

print("A = ")
print(A)

print("\nB = ")
print(B)

print("\nA e B são o mesmo objeto?")
print(B is A)

print(f"\nid(A): {id(A)}, id(B): {id(B)}") ## A e B possuem o mesmo id

A = 
[[  0. 100.   0.]
 [  0. 100.   0.]
 [  0. 100.   0.]]

B = 
[[  0. 100.   0.]
 [  0. 100.   0.]
 [  0. 100.   0.]]

A e B são o mesmo objeto?
True

id(A): 140411974265680, id(B): 140411974265680


In [41]:
## No entanto, pode-se gerar uma cópia
import numpy as np

A = np.zeros((3,3))

B = A.copy()    ## atribuição não é cópia

A[:,1] = 100    ## note que ao alterar "A", a matriz "B" ainda será a mesma.

print("A = ")
print(A)

print("\nB = ")
print(B)

print("\nA e B são o mesmo objeto?")
print(B is A)


print(f"\nid(A): {id(A)}, id(B): {id(B)}") ## A e B possuem id's diferentes

A = 
[[  0. 100.   0.]
 [  0. 100.   0.]
 [  0. 100.   0.]]

B = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

A e B são o mesmo objeto?
False

id(A): 140411973810096, id(B): 140411974266352


O Python passa objetos mutáveis por referência para funções, de modo que a chamada de uma função não faz uma cópia.

>  Se um objeto passado por referência for modificado dentro de uma função, ele também será modificado fora dela.

In [42]:
def f(x):
  return id(x)

a = np.zeros((3,3))

print(id(a))    # ID é o identificador único do objeto
print(f(a))     # mesmo ID


140411973627952
140411973627952


Ou seja, se o objeto for alterado dentro da função, então ele será alterado também fora da função.

In [43]:
def f(x):
  x[:, 1] = 100
  return;

A = np.zeros((3,3))
f(A)
print(A)     # "A" foi modificada dentro da função

[[  0. 100.   0.]
 [  0. 100.   0.]
 [  0. 100.   0.]]


Para evitar este possível problema, pode-se passar um cópia.

In [44]:
def f(x):
  x[:, 1] = 100
  return;

A = np.zeros((3,3))

f( A.copy() )  # A cópia de "A" é passada para a função

print(A)       # A matriz "A" continua a mesma

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Diferentes matrizes podem compartilhar o mesmo dado. O método `view` cria uma visualização da matriz.

In [45]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a, "\n")

c = a.view()

print(c is a, "\n")      ## "c" é uma visualização de "a"

c = c.reshape((2, 6))    ## Não muda a dimensão de 'a'
print(a.shape, "\n")

c[0, 4] = 100            ## Muda os dados em 'a'
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

False 

(3, 4) 

[[  0   1   2   3]
 [100   5   6   7]
 [  8   9  10  11]]


Fatiar uma matriz retorna uma visualização:

In [46]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print("a:\n",a,"\n")

s = a[:, 1:3]          # "s" é uma visualização de uma parte de "a".
print("s:\n",s,"\n")

print(s is a, "\n")

s[:] = 10              # s[:] é uma visualização de 's'.
print("s:\n",s,"\n")

print("a:\n",a,"\n")   # ao alterar "s", o objeto "a" também foi alterado.

a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

s:
 [[ 1  2]
 [ 5  6]
 [ 9 10]] 

False 

s:
 [[10 10]
 [10 10]
 [10 10]] 

a:
 [[ 0 10 10  3]
 [ 4 10 10  7]
 [ 8 10 10 11]] 



## Exercício 5

1. Crie uma matriz A de tamanho 4x3 de zeros.
1. Faça `B=A` e `C=A.copy()`.
1. Verifique se `B` e `C` são os mesmos objetos utilizando `is`.
1. Mostre os id's de `A`, `B` e `C`.
1. Altere um elemento de `A` e veja o que acontece com `B` e com `C`.